import os
from datetime import datetime
import openpyxl as op
from tkinter import messagebox,
import shutil

erros = {0 : 'REGISTRO AR - ASSINADO',
2 : 'PRIMEIRO REGISTRO NAO E HEADER/SEQUENCIA DIFERENTE DE 1',
3 : 'REGISTRO DIFERENTE DE 0, 1 E 9',
4 : 'REGISTRO FORA DE SEQUENCIA',
5 : 'REGISTRO TRAILLER NAO INFORMADO',
8 : 'CODIGO DE OPERACAO DIFERENTE DE E, I',
9 : 'TIPO DE PESSOA PRINCIPAL DIFERENTE DE F, J',
10 : 'TIPO DE PESSOA COOBRIGADO DIFERENTE DE F, J',
11 : 'NOME INVALIDO',
12 : 'NOME NAO PODE SER BRANCOS',
13 : 'DATA DO HEADER INVALIDA',
14 : 'DATA DA OCORRENCIA INVALIDA',
16 : 'DATA DA OCORRENCIA MAIOR QUE A ATUAL',
17 : 'DATA DA OCORRENCIA JA DECURSADA',
18 : 'IDENTIFICACAO DO ARQUIVO INVALIDA',
19 : 'REMESSA NAO POSTERIOR A ULTIMA',
20 : 'REMESSA NAO NUMERICA OU IGUAL A ZERO',
21 : 'CAMPO DE RECEBIMENTO DA REMESSA DIFERENTE DE E',
22 : 'EXCLUSAO PARA REGISTRO INEXISTENTE',
24 : 'CNPJ DO HEADER INVALIDO',
25 : 'CNPJ NAO CADASTRADO NO SISTEMA (TABELA DE REMESSA)',
28 : 'DOCUMENTO DO PRINCIPAL NAO NUMERICO',
29 : 'DOCUMENTO DO PRINCIPAL INVALIDO',
30 : 'DOCUMENTO DO COOBRIGADO NAO NUMERICO',
31 : 'DOCUMENTO DO COOBRIGADO INVALIDO',
33 : 'TRAILLER FORA DE SEQUENCIA',
34 : 'SEQUENCIA NAO NUMERICA',
40 : 'REG. NAO ATUALIZADO. ERRO NO PRINCIPAL OU COOBRIGADO DA OCORRENCIA',
44 : 'AGENCIA INVALIDA',
47 : 'CONTA NAO NUMERICA',
59 : 'INCLUSAO PARA REGISTRO JA EXISTENTE',
64 : 'CONTA INVALIDA',
65 : 'CHEQUE INVALIDO',
72 : 'ALINEA INVALIDA',
81 : 'REGISTRO APOS TRAILLER',
85 : 'NUMERO DO CONTRATO/TITULO INVALIDO',
89 : 'EMPRESA NAO PARTICIPANTE DO CONVENIO',
102 : 'NUMERO DO CONTRATO/TITULO EH OBRIGATORIO',
103 : 'TIPO DE DOCUMENTO INVALIDO',
105 : 'INCLUSAO BLOQUEADA FACE A DETERMINACAO ADMINISTRATIVA',
106 : 'MOVIMENTO APOS RESCISAO DE CONTRATO DO CONVENIO',
109 : 'FALTA ENDERECO',
111 : 'FALTA UF DO ENDERECO',
112 : 'FALTA CEP DO ENDERECO',
113 : 'FALTA INFORMACAO TIPO DE PESSOA',
115 : 'TIPO DE PESSOA DO PRINCIPAL DIFERENTE DE F',
116 : 'TIPO DE PESSOA DO COOBRIGADO DIFERENTE DE F',
119 : 'CEP DO ENDERECO INVALIDO',
121 : 'DATA DE NASCIMENTO INFERIOR A 18 ANOS',
142 : 'BANCO NAO TRABALHA COM CONTA CORRENTE',
156 : 'DATA OCORRENCIA INFERIOR A 1 DIA',
166 : 'DATA DE TERMINO DO CONTRATO INVALIDA',
169 : 'AREA INFORMANTE DA REMESSA C/ ERRO. MOVIMENTO REJEITADO',
170 : 'BANCO INVALIDO P/ NATUREZA DE/DC',
171 : 'TIPO DE PESSOA DO CREDOR DIFERENTE DE F, J',
172 : 'TIPO DE DOCUMENTO DO CREDOR INVALIDO',
173 : 'DOCUMENTO DO CREDOR NAO NUMERICO',
174 : 'DOCUMENTO DO CREDOR INVALIDO',
175 : 'NOME DO CREDOR EH OBRIGATORIO',
176 : 'NOME DO CREDOR INVALIDO',
200 : 'BANCO DO HEADER INVALIDO',
205 : 'BANCO NAO CADASTRADO NO SISTEMA (TABELA DE BANCOS)',
219 : 'VALOR DO TITULO INVALIDO',
263 : 'IDENTIFICACAO DO ARQUIVO INVALIDA',
274 : 'CNPJ NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
275 : 'CPF NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
276 : 'FILIAL NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
277 : 'CNPJ CREDOR/CEDENTE NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
278 : 'CPF CREDOR/CEDENTE NAO EXISTE NO CADASTRO DE CNPJ/CPF ATE ESTA DATA',
279 : 'FILIAL CREDOR/CEDENTE NAO EXISTE CADASTRO DE CNPJ/CPF ATE ESTA DATA',
286 : 'DOCUMENTO DO CREDOR IGUAL AO DO NEGATIVADO',
290 : 'EXCLUSAO POR DATA DE OCORRENCIA JA DECURSADA',
291 : 'EXCLUSAO POR DETERMINACAO JUDICIAL',
292 : 'EXCLUSAO POR SOLICITACAO DA EMPRESA PARTICIPANTE',
295 : 'RAZAO SOCIAL NAO CORRESPONDE AO CNPJ INFORMADO',
296 : 'NOME NAO CORRESPONDE AO CPF INFORMADO',
298 : 'COOBRIGADO NAO INCLUIDO - PRINCIPAL NAO ENCONTRADO',
301 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - MUDOU-SE',
302 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - END INSUFICIENTE',
303 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - NR INEXISTENTE',
304 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - DESCONHECIDO',
305 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - RECUSADO',
306 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - NAO PROCURADO',
307 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - AUSENTE',
308 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - FALECIDO',
309 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - INFORM P/ PORTEIRO',
310 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - END N CONHECIDO',
311 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - CEP INCORRETO',
312 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO DO CORREIO - N ESPECIFICADO',
313 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - CX POSTAL INEXIST',
314 : 'REGISTRO ESPECIAL - DEVOLUCAO COMUNICADO CORREIO - IMOVEL INEXISTENTE',
315 : 'DEVIDO A DEVOLUCAO DO COMUNICADO DO CORREIO',
316 : 'REGISTRO AR - EXTRAVIADO',
317 : 'REGISTRO AR - ROUBADO',
318 : 'REGISTRO AR - AUSENTE - ENCAMINHADO PARA ENTREGA INTERNA',
319 : 'REGISTRO AR - REFUGADO',
320 : 'REGISTRO AR - ENDERECO INCORRETO',
321 : 'REGISTRO AR - NAO PROCURADO – DEVOLVIDO AO REMETENTE',
322 : 'REGISTRO AR - DOCUMENTACAO NAO FORNECIDA',
323 : 'REGISTRO AR - MUDOU-SE',
324 : 'REGISTRO AR - DESCONHECIDO',
325 : 'REGISTRO AR - RECUSADO',
326 : 'REGISTRO AR - ENDERECO INSUFICIENTE',
327 : 'REGISTRO AR - NAO EXISTE O NUMERO INDICADO',
328 : 'REGISTRO AR - AUSENTE',
329 : 'REGISTRO AR - NAO PROCURADO',
330 : 'REGISTRO AR - FALECIDO',
331 : 'REGISTRO AR - DEVIDO A DEVOLUCAO DO COMUNICADO DO CORREIO',
356 : 'DATA DO COMPROMISSO MAIOR QUE A ATUAL',
357 : 'DATA DO COMPROMISSO INVALIDA',
358 : 'VALOR DO COMPROMISSO NAO NUMERICO',
359 : 'DDD INVALIDO',
360 : 'TELEFONE INVALIDO',
390 : 'INCLUSAO RECUSADA - PARTICIPANTE COM LOGON BLOQUEADO',
391 : 'REGISTRO REJEITADO - INCONSISTENCIA NO HEADER',
392 : 'FALTA CODIGO CLIENTE NA RSREMESSA OU CODIGO NAO TEM 5 CARACTERE',
394 : 'CNPJ NAO CORRESPONDE AO CODIGO DE CLIENTE INFORMADO',
396 : 'INCLUSAO REJEITADA-VLR.CONS.ELEVADO-NEGAT.PRIMARIA-INCL.SISCONVEM',
488 : 'PARTICIPANTE NAO POSSUI PROCURACAO DO CREDOR',
489 : 'UF DO RG INVALIDO',
490 : 'FALTAM DADOS CADASTRAIS DO CREDOR DA DIVIDA',
491 : 'MUNICIPIO NAO CORRESPONDE AO CEP E/OU UF INFORMADO',
600 : 'MENSAGEM NAO INFORMADA PELO GERENCIADOR',
610 : 'INCLUSAO CONDICIONADA A APRESENTACAO DE DOCTO DA DIVIDA',
650 : 'CODIGO DO BANCO INVALIDO',
651 : 'BANCO NAO CADASTRADO',
652 : 'DIGITO DO CODIGO DO BANCO INVALIDO',
653 : 'NOME DO BANCO NAO INFORMADO',
654 : 'CARACTERES DA LINHA DIGITAVEL INVALIDA',
655 : 'PRIMEIRO DIGITO DA LINHA DIGITAVEL DIVERGENTE',
656 : 'SEGUNDO DIGITO DA LINHA DIGITAVEL DIVERGENTE',
657 : 'TERCEIRO DIGITO DA LINHA DIGITAVEL DIVERGENTE',
658 : 'QUARTO DIGITO DA LINHA DIGITAVEL DIVERGENTE',
659 : 'TEXTO DO LOCAL DE PAGAMENTO NAO INFORMADO',
660 : 'DATA DE VENCIMENTO DO BOLETO INVALIDA',
661 : 'DATA DE VENCIMENTO DO BOLETO MENOR QUE A DATA DE HOJE',
662 : 'TIPO DE PESSOA DO DOCUMENTO DO CEDENTE INVALIDO',
663 : 'TIPO DE DOCUMENTO DO CEDENTE DIVERGENTE DO TIPO DE PESSOA',
664 : 'DOCUMENTO DO CEDENTE INVALIDO',
665 : 'DIGITO DO DOCUMENTO DO CEDENTE INVALIDO',
666 : 'AGENCIA E CODIGO DO CEDENTE NAO INFORMADO',
667 : 'DATA DO DOCUMENTO INVALIDA',
668 : 'NUMERO DO DOCUMENTO NAO INFORMADO',
669 : 'DATA DO PROCESSAMENTO INFORMADA E INVALIDA',
670 : 'NOSSO NUMERO NAO INFORMADO',
671 : 'QUANTIDADE DE MOEDA NAO INFORMADA',
672 : 'QUANTIDADE DE MOEDA INVALIDA',
673 : 'QUANTIDADE DE DECIMAIS DA MOEDA NAO INFORMADA',
674 : 'QUANTIDADE DE DECIMAIS DA MOEDA INVALIDA',
675 : 'QUANTIDADE DE DECIMAIS DA MOEDA MAIOR QUE 5 CASAS DECIMAIS',
676 : 'VALOR DA MOEDA NAO INFORMADO',
677 : 'VALOR DA MOEDA INVALIDA',
678 : 'VALOR DO DOCUMENTO INVALIDO',
679 : 'VALOR DE OUTROS ACRESCIMOS INVALIDO',
680 : 'VALOR DE DESCONTOS/ABATIMENTO INVALIDO',
681 : 'VALOR DE OUTRAS DEDUCOES INVALIDO',
682 : 'VALOR DE MORA/MULTA INVALIDO',
683 : 'VALOR COBRADO INVALIDO',
684 : 'TIPO DE PESSOA DO DOCUMENTO DO SACADOR INVALIDO',
685 : 'TIPO DE DOCUMENTO DO SACADOR DIVERGENTE DO TIPO DE PESSOA',
686 : 'DOCUMENTO DO SACADOR INVALIDO',
687 : 'DIGITO DO DOCUMENTO DO SACADOR INVALIDO',
701 : 'EXISTE DADOS BOLETO E NAO INFORMADO INDICATIVO DE TIPO DE COMUNICADO',
702 : 'INDICATIVO DE TIPO DE COMUNICADO DIFERENTE DE BRANCO OU B',
703 : 'TIPO DE COMUNICADO COMO BOLETO E NAO FOI INFORMADO O REG.TP 2 E/OU 3',
704 : 'TIPO DE COMUNICADO BOLETO NAO PERMITIDO PARA COOBRIGADO',
705 : 'REG BOLETO TIPO 2 ENCONTRADO, SEM REGISTRO TIPO 1 CORRESPONDENTE',
706 : 'REG BOLETO TIPO 3 ENCONTRADO, SEM REGISTRO TIPO 1 CORRESPONDENTE',
707 : 'PARTICIPANTE NAO POSSUI CONTRATO PARA EMISSAO DE COMUNICADO COM BOLETO',
721 : 'ENDERECO DO CEDENTE NAO CADASTRADO',
739 : 'PARTICIPANTE NAO POSSUI CONTRATO PARA EMISSAO DE SMS.',
740 : 'TELEFONE CELULAR INEXISTENTE',
745 : 'INCLUSOES REJEITADAS - ESCRITORIO DE COBRANCA'}


def config_card(cartao):
    if len(cartao) == 16:
        return f"{cartao[0:4]}.{cartao[4:8]}.{cartao[8:12]}.{cartao[12:16]}"
    else:
        return cartao
def lerSerasa(filediretory):
    size = (os.path.getsize(filediretory)) / (1024 * 1024)
    remessa = None
    cards = []
    with open(filediretory, 'r') as files:
        rows = files.readlines()
        remessa = rows[0][117:125]
        for row in rows:
            if row[438:454].strip() != '':
                cards.append(row[438:454].strip())
    return remessa, cards, size

def lerRetSerasa(remessadiretory, retdiretory):
    remessa, cards, size = lerSerasa(remessadiretory)
    with open(retdiretory, 'r') as fileret:
        rows = fileret.readlines()
        remessaret = rows[0][117:125]
        vencimentof = (datetime.strptime(rows[1][8:16].strip(), "%Y%m%d")).strftime("%d-%m-%Y")
        excel = op.Workbook()
        a = excel['Sheet']
        a.append(['NOME', 'CPF', 'DATA DE NASCIMENTO ', 'CARTÃO', 'VALOR', 'VENCIMENTO', 'STATUS'])

        for row in rows:
            if remessa == remessaret and '1' in row[0:1]:
                nome = row[105:175].rstrip()
                cpf = F'{row[37:40]}.{row[40:43]}.{row[43:46]}-{row[46:48]}'  # 48
                cartao = row[438:454].rstrip()
                erro = row[533:540].strip().lstrip('0')
                valor = f'{row[423:436].lstrip('0')},{row[436:438]}'
                vencimento = row[8:16].strip()
                datanasc = (datetime.strptime(row[175:183], "%Y%m%d")).strftime("%d/%m/%Y")
                data_obj = datetime.strptime(vencimento, "%Y%m%d")
                data_formatada = data_obj.strftime("%d/%m/%Y")
                if not erro:
                    a.append([nome, cpf, datanasc, config_card(cartao), valor, data_formatada,
                              'INCLUSO'])
                else:
                    erro = int(erro)
                    a.append([nome, cpf, datanasc, config_card(cartao), valor, data_formatada,
                              erros[erro]])
        try:
            os.makedirs(f'Retornos/VENCIMENTO {vencimentof}')
        except Exception as e:
            pass

        excel.save(f'Retornos/VENCIMENTO {vencimentof}/SERASA {vencimentof}.xlsx')
        diretory = os.path.join('Retornos/Vencimento', f'Vencimento {vencimentof}.xlsx')
        messagebox.showinfo('MoonInc', f'Salvo em {diretory}')





