from enum import Enum

class PathNames(Enum):
    CREDITOVISA = '1 - CREDITO VISA'
    DEBITOVISA = '2 - DEBITO VISA'
    CREDITOMASTERCARD = '3 - CREDITO MASTERCARD'
    DEBITOMASTERCARD = '4 - DEBITO MASTERCARD'
    CREDITOELO = '5 - CREDITO ELO'
    DEBITOELO = '6 - DEBITO ELO'
    CREDITOHIPERCARD = '7 - CREDITO HIPERCARD'
